### ISSUE TITLE
brew install comply error

### ISSUE THREAD

**Issue by ghost** [strongdm/homebrew-comply#1]
brew install comply
Updating Homebrew...
==> Auto-updated Homebrew!
Updated 1 tap (homebrew/core).
==> Updated Formulae
Updated 2 formulae.

==> Installing comply from strongdm/comply
==> Downloading https://homebrew.bintray.com/bottles/go-1.16.big_sur.bottle.tar.gz
Already downloaded: /Users/jerimiah/Library/Caches/Homebrew/downloads/1860d1cb8f63bb63c1d0ad2ad7d3ef8674f177c83ad66428c47114cc4abbe60b--go-1.16.big_sur.bottle.tar.gz
==> Downloading https://github.com/strongdm/comply/archive/v1.5.1.tar.gz
Already downloaded: /Users/jerimiah/Library/Caches/Homebrew/downloads/aa4bb8ed781fe561a2ce511a8705eafc91bd8112763b75bd2f432be12e694430--comply-1.5.1.tar.gz
==> Installing dependencies for strongdm/comply/comply: go
==> Installing strongdm/comply/comply dependency: go
==> Pouring go-1.16.big_sur.bottle.tar.gz
🍺  /usr/local/Cellar/go/1.16: 9,967 files, 503.5MB
==> Installing strongdm/comply/comply
==> make brew
Last 15 lines from /Users/jerimiah/Library/Logs/Homebrew/comply/01.make:
go: downloading github.com/google/go-querystring v1.0.0
go: downloading github.com/trivago/tgo v1.0.7
go: downloading github.com/fatih/structs v1.1.0
go: downloading github.com/russross/blackfriday v1.5.3-0.20200218234912-41c5fccfd6f6
go: downloading github.com/hashicorp/go-retryablehttp v0.6.7
go: downloading github.com/hashicorp/go-cleanhttp v0.5.1
go: downloading golang.org/x/time v0.0.0-20200630173020-3af7569d3a1e
go: downloading github.com/fsnotify/fsnotify v1.4.9
go: downloading github.com/docker/go-units v0.4.0
go: downloading github.com/docker/go-connections v0.4.0
go: downloading github.com/docker/distribution v2.7.1+incompatible
go: downloading github.com/opencontainers/go-digest v1.0.0
../../../../pkg/mod/github.com/cpuguy83/go-md2man/v2@v2.0.0/md2man/md2man.go:4:2: missing go.sum entry for module providing package github.com/russross/blackfriday/v2 (imported by github.com/cpuguy83/go-md2man/v2/md2man); to add:
	go get github.com/cpuguy83/go-md2man/v2/md2man@v2.0.0
make: *** [brew] Error 1

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
  https://github.com/strongdm/homebrew-comply/issues

**Comment by Baptiste-Leterrier** [comment]
Also got the same error:

```
brew tap strongdm/comply; brew install comply
==> Installing comply from strongdm/comply
==> Downloading https://homebrew.bintray.com/bottles/go-1.16.2.big_sur.bottle.tar.gz
Already downloaded: /Users/bleterrier/Library/Caches/Homebrew/downloads/193509b23cb756ff1d95e4eb1722225a172ce8916791c1c32f42ee055e5470ec--go-1.16.2.big_sur.bottle.tar.gz
==> Downloading https://github.com/strongdm/comply/archive/v1.5.1.tar.gz
Already downloaded: /Users/bleterrier/Library/Caches/Homebrew/downloads/aa4bb8ed781fe561a2ce511a8705eafc91bd8112763b75bd2f432be12e694430--comply-1.5.1.tar.gz
==> Installing dependencies for strongdm/comply/comply: go
==> Installing strongdm/comply/comply dependency: go
==> Pouring go-1.16.2.big_sur.bottle.tar.gz
🍺  /usr/local/Cellar/go/1.16.2: 9,948 files, 503.4MB
==> Installing strongdm/comply/comply
==> make brew
Last 15 lines from /Users/bleterrier/Library/Logs/Homebrew/comply/01.make:
go: downloading github.com/jcelliott/lumber v0.0.0-20160324203708-dd349441af25
go: downloading github.com/dgrijalva/jwt-go v3.2.0+incompatible
go: downloading github.com/fatih/structs v1.1.0
go: downloading github.com/google/go-querystring v1.0.0
go: downloading github.com/trivago/tgo v1.0.7
go: downloading github.com/hashicorp/go-cleanhttp v0.5.1
go: downloading github.com/hashicorp/go-retryablehttp v0.6.7
go: downloading golang.org/x/time v0.0.0-20200630173020-3af7569d3a1e
go: downloading github.com/fsnotify/fsnotify v1.4.9
go: downloading github.com/russross/blackfriday v1.5.3-0.20200218234912-41c5fccfd6f6
go: downloading github.com/opencontainers/go-digest v1.0.0
go: downloading github.com/lunixbochs/vtclean v1.0.0
../../../../pkg/mod/github.com/cpuguy83/go-md2man/v2@v2.0.0/md2man/md2man.go:4:2: missing go.sum entry for module providing package github.com/russross/blackfriday/v2 (imported by github.com/cpuguy83/go-md2man/v2/md2man); to add:
	go get github.com/cpuguy83/go-md2man/v2/md2man@v2.0.0
make: *** [brew] Error 1

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
  https://github.com/strongdm/homebrew-comply/issues

These open issues may also help:
brew install comply error https://github.com/strongdm/homebrew-comply/issues/1
```

**Comment by nickvth** [comment]
Same issue here

**Comment by leanne-micruity** [comment]
Same issue here.

**Comment by AstroBoy269** [comment]
Not to pile on but having the same issue on BigSur 11.2.3 on a 2018 Mac mimi.
```==> Installing comply from strongdm/comply
==> Downloading https://github.com/strongdm/comply/archive/v1.5.1.tar.gz
Already downloaded: /Users/lcr/Library/Caches/Homebrew/downloads/aa4bb8ed781fe561a2ce511a8705eafc91bd8112763b75bd2f432be12e694430--comply-1.5.1.tar.gz
==> make brew
Last 15 lines from /Users/lcr/Library/Logs/Homebrew/comply/01.make:
go: downloading github.com/hashicorp/go-cleanhttp v0.5.1
go: downloading github.com/hashicorp/go-retryablehttp v0.6.7
go: downloading golang.org/x/time v0.0.0-20200630173020-3af7569d3a1e
go: downloading github.com/jcelliott/lumber v0.0.0-20160324203708-dd349441af25
go: downloading github.com/docker/go-connections v0.4.0
go: downloading github.com/docker/go-units v0.4.0
go: downloading github.com/docker/distribution v2.7.1+incompatible
go: downloading golang.org/x/net v0.0.0-20200904194848-62affa334b73
go: downloading github.com/lunixbochs/vtclean v1.0.0
go: downloading github.com/russross/blackfriday v1.5.3-0.20200218234912-41c5fccfd6f6
go: downloading github.com/fsnotify/fsnotify v1.4.9
go: downloading github.com/opencontainers/go-digest v1.0.0
../../../../pkg/mod/github.com/cpuguy83/go-md2man/v2@v2.0.0/md2man/md2man.go:4:2: missing go.sum entry for module providing package github.com/russross/blackfriday/v2 (imported by github.com/cpuguy83/go-md2man/v2/md2man); to add:
	go get github.com/cpuguy83/go-md2man/v2/md2man@v2.0.0
make: *** [brew] Error 1

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
  https://github.com/strongdm/homebrew-comply/issues```

**Comment by shortstack** [comment]
same :(

**Comment by Yuxael** [comment]
same error on Catalina 10.15.7

**Comment by bendok** [comment]
Same

**Comment by tussock** [comment]
Hate to pile on too... but same issue here
on Big Sur 11.3

Given the amount of time that has passed since this was first reported, I'm guessing that this issue tracker is not monitored or checked.

**Comment by emreozen** [comment]
Having the same issue on Big Sur 11.3 - any workarounds?

**Comment by leanne-micruity** [comment]
We ended up going with Drata.com. They're not free, but they've got a great system and awesome customer service. We're saving major $$ and dev work with their built in monitoring tools.

**Comment by jmccarthy** [comment]
Resolved by https://github.com/strongdm/homebrew-comply/commit/ca7bf9b009c67fb9f61bcaacfd4f30611aa3536d - thanks for the report!
